export const environment = {
  SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL || "",
  SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "",
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY || "",
  NEXT_PUBLIC_MIDTRANS_API_URL: process.env.NEXT_PUBLIC_MIDTRANS_API_URL || "",
  NEXT_PUBLIC_MIDTRANS_ClIENT_KEY:
    process.env.NEXT_PUBLIC_MIDTRANS_ClIENT_KEY || "",
  MIDTRANS_SERVER_KEY: process.env.MIDTRANS_SERVER_KEY || "",
};
